name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        goversion: [1.19, "1.20", "1.21"]
    steps:
      - name: Set up Go ${{matrix.goversion}} on ${{matrix.os}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.goversion}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: gofmt
        run: |
          [[ -z  $(gofmt -l $(find . -name '*.go') ) ]]

      - name: Get dependencies
        env:
          GO111MODULE: on
        run: go mod download

      - name: Vet
        env:
          GO111MODULE: on
        run: go vet -mod=readonly ./...

      - name: Test
        env:
          GO111MODULE: on
        run: go test -mod=readonly -v -count 2 ./...

      - name: Race Test
        env:
          GO111MODULE: on
        run: go test -race -mod=readonly -v -count 2 ./...
